# Generated by Django 2.2.3 on 2019-08-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(default='이력서 템플릿', max_length=50)),
                ('file', models.FileField(null=True, upload_to='resume_templates')),
                ('download_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('info_name', models.CharField(max_length=50)),
                ('writer_name', models.CharField(max_length=20)),
                ('writer_address', models.TextField()),
                ('writer_phone', models.CharField(max_length=13)),
                ('writer_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeMerged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx_file', models.FileField(null=True, upload_to='')),
                ('pdf_file', models.FileField(null=True, upload_to='')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docxmerge.Resume')),
                ('resume_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docxmerge.ResumeInfo')),
            ],
        ),
    ]
