# Generated by Django 2.2.2 on 2019-07-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxmerge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateTimeField(default='2019. 07. 10.'),
        ),
    ]
