# Generated by Django 2.2.3 on 2019-07-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docxmerge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='writer_address',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='writer_email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='writer_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='writer_phone',
        ),
        migrations.AddField(
            model_name='resume',
            name='download_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to='resume_templates'),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(default='이력서 템플릿', max_length=50),
        ),
        migrations.CreateModel(
            name='ResumeMerged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx_file', models.FileField(null=True, upload_to='')),
                ('pdf_file', models.FileField(null=True, upload_to='')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docxmerge.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('writer_name', models.CharField(max_length=20)),
                ('writer_address', models.TextField()),
                ('writer_phone', models.CharField(max_length=13)),
                ('writer_email', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docxmerge.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resume')},
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='docxmerge.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
