# Generated by Django 2.2.3 on 2019-08-01 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docxmerge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemerged',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='download_user_set',
            field=models.ManyToManyField(blank=True, related_name='download_user_set', through='docxmerge.Download', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='docxmerge.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docxmerge.Resume'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='download',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docxmerge.Resume'),
        ),
        migrations.AddField(
            model_name='download',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'resume')},
        ),
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('user', 'resume')},
        ),
    ]
