# Generated by Django 2.2.2 on 2019-07-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxmerge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='writer_phone',
            field=models.CharField(max_length=13),
        ),
    ]
