# Generated by Django 2.2.2 on 2019-07-17 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docxmerge', '0002_auto_20190717_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='writer_address',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='writer_email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='writer_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='writer_phone',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False), max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('writer_name', models.CharField(max_length=20)),
                ('writer_address', models.TextField()),
                ('writer_phone', models.CharField(max_length=13)),
                ('writer_email', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
