# Generated by Django 2.2.2 on 2019-07-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxmerge', '0002_auto_20190710_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
