# Generated by Django 2.2.2 on 2019-07-18 02:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docxmerge', '0003_auto_20190717_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to='resume_templates'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
