# Generated by Django 2.2.2 on 2019-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxmerge', '0003_auto_20190710_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
