# Generated by Django 2.2.2 on 2019-07-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxmerge', '0004_auto_20190716_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='writer_phone',
            field=models.CharField(max_length=13),
        ),
    ]
