# Generated by Django 2.2.3 on 2019-07-19 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docxmerge', '0004_auto_20190718_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='download_num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ResumeMerged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('file', models.FileField(null=True, upload_to='resume_users')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docxmerge.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docxmerge.Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resume')},
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='like_num',
            field=models.ManyToManyField(blank=True, related_name='like_num', through='docxmerge.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
