# Generated by Django 2.2.3 on 2019-07-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxmerge', '0006_auto_20190719_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumemerged',
            old_name='file',
            new_name='docx_file',
        ),
        migrations.RemoveField(
            model_name='resumemerged',
            name='path',
        ),
        migrations.AddField(
            model_name='resumemerged',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
