# Generated by Django 2.2.2 on 2019-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(max_length=20)),
                ('writer_address', models.TextField()),
                ('writer_phone', models.CharField(max_length=11)),
                ('writer_email', models.CharField(max_length=30)),
            ],
        ),
    ]
